metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.10.10.11, mac: '00:23:24:b6:a6:f3', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal1: {ansible_host: 10.10.10.12, mac: '00:23:24:b6:a6:e4', disk: sda, network_interface: eno1}
